DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ NOCACHE;

DROP TABLE MEMBER;
CREATE TABLE MEMBER(
	NO NUMBER NOT NULL,
	ID VARCHAR2(30 BYTE) NOT NULL UNIQUE,
	PW VARCHAR2(30 BYTE) NOT NULL,
	NAME VARCHAR2 (15 BYTE) NOT NULL,
	EMAIL VARCHAR2 (100 BYTE) NOT NULL,
	CONSTRAINT MEMBER_PK PRIMARY KEY(NO)
);

SELECT *
FROM MEMBER;