DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE;

DROP TABLE BOARD;
CREATE TABLE BOARD (
	BOARD_NO NUMBER NOT NULL,
	WRITER VARCHAR2(20 BYTE) NOT NULL,
	TITLE VARCHAR2(20 BYTE) NOT NULL,
	CONTENT VARCHAR2(300 BYTE),
	CREATE_DATE VARCHAR2(10 BYTE),
	CONSTRAINT PK_BOARD PRIMARY KEY(BOARD_NO)
);

INSERT INTO BOARD
			(BOARD_NO, WRITER, TITLE, CONTENT, CREATE_DATE)
		VALUES
			(1, 'A', 'b', 'd', 'd');
	

SELECT *
 FROM BOARD;